# Generated by Django 3.1.2 on 2020-12-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('rollno', models.ImageField(upload_to='')),
                ('marks', models.ImageField(upload_to='')),
                ('gf', models.CharField(max_length=64)),
                ('bf', models.CharField(max_length=64)),
            ],
        ),
    ]
